[package]
name = "service_eazymana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
service_eazypic = {path = "../service_eazypic"}
common_aws = {path = "../common_aws"}