version: '3.8'
services:
  api:
    image: vanha777/service_eazypic:latest
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "1010:1010"
    environment:
      - PORT=1010