version: '3.8'
services:
  api:
    image: vanha777/service_docurust:latest
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3070:3070"
    environment:
      - PORT=3070